MicroserviceUser/Models/ErrorViewModel.cs
using System;

namespace MicroserviceUser.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MicroserviceUser/Models/Libro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MicroserviceUser.Models
{
    public class Libro
    {
        [Key]
        public int Id { get; set; }
        //le muestra al usuario que es obligatorio
        [Required(ErrorMessage = "el titulo es obligatorio")]
        //Obliga al usuario a tener entre 3 y 50 caracteres y si no cumple nos arroja un mensaje
        [StringLength(50, ErrorMessage = "EL {0} debe ser al menos {2} y maximo {1} caracteres", MinimumLength = 3)]
        //Esto es por si necesitamos que sea con tilde pero en DB no tiene tilde
        [Display(Name = "Tìtulo")]

        public string titulo { get; set; }

        [Required(ErrorMessage = "la descripcion es obligatorio")]
        [StringLength(50, ErrorMessage = "EL {0} debe ser al menos {2} y maximo {1} caracteres", MinimumLength = 3)]
        [Display(Name = "Descripciòn")]

        public string descripcion { get; set; }

        [Required(ErrorMessage = "la fecha es obligatorio")]
        //Aca le damos formato a la hora, solo queremos la fecha
        [DataType(DataType.Date)]

        public DateTime fechaDeLanzamiento { get; set; }

        [Required(ErrorMessage = "el autor es obligatorio")]
        public string Autor { get; set; }
        [Required(ErrorMessage = "el precio es obligatorio")]

        public int precio { get; set; }
    }
}

MicroserviceUser/Controllers/HomeController.cs
using MicroserviceUser.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MicroserviceUser.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MicroserviceUser/Controllers/LibrosController.cs
using MicroserviceUser.Data;
using MicroserviceUser.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MicroserviceUser.Controllers
{
    public class LibrosController : Controller
    {
        private readonly ApplicationDbContext _context;
        public LibrosController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<Libro> listLibros = _context.Libro;
            return View(listLibros);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Libro libro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(libro);
                _context.SaveChanges();
                TempData["Mensaje"] = "Guardado exitosamente";
                return RedirectToAction("index");
            }
            return View();
        }



        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var libro = _context.Libro.Find(id);

            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }
        [HttpPost]
        public IActionResult Edit(Libro libro)
        {
            if (ModelState.IsValid)
            {
                _context.Libro.Update(libro);
                _context.SaveChanges();
                TempData["Mensaje"] = "Actualizado exitosamente";

                return RedirectToAction("index");
            }
            return View();
        }
        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var libro = _context.Libro.Find(id);

            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        [HttpPost]
        public IActionResult DeleteLibro(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var libro = _context.Libro.Find(id);

            if (libro == null)
            {
                return NotFound();
            }
            _context.Libro.Remove(libro);
            _context.SaveChanges();

            return RedirectToAction("index");
        }

    }
}

MicroserviceUser/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MicroserviceUser/Views/Libros/Create.cshtml
@model MicroserviceUser.Models.Libro

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Create</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="titulo" class="control-label"></label>
                <input asp-for="titulo" class="form-control" />
                <span asp-validation-for="titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fechaDeLanzamiento" class="control-label"></label>
                <input asp-for="fechaDeLanzamiento" class="form-control" />
                <span asp-validation-for="fechaDeLanzamiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="precio" class="control-label"></label>
                <input asp-for="precio" class="form-control" />
                <span asp-validation-for="precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MicroserviceUser/Views/Libros/Delete.cshtml
@model MicroserviceUser.Models.Libro

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DeleteLibro" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="titulo" class="control-label"></label>
                <input asp-for="titulo" class="form-control" disabled/>
                <span asp-validation-for="titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" disabled />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fechaDeLanzamiento" class="control-label"></label>
                <input asp-for="fechaDeLanzamiento" class="form-control" disabled/>
                <span asp-validation-for="fechaDeLanzamiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" disabled/>
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="precio" class="control-label"></label>
                <input asp-for="precio" class="form-control" disabled />
                <span asp-validation-for="precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MicroserviceUser/Views/Libros/Edit.cshtml
@model MicroserviceUser.Models.Libro

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="titulo" class="control-label"></label>
                <input asp-for="titulo" class="form-control" />
                <span asp-validation-for="titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fechaDeLanzamiento" class="control-label"></label>
                <input asp-for="fechaDeLanzamiento" class="form-control" />
                <span asp-validation-for="fechaDeLanzamiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="precio" class="control-label"></label>
                <input asp-for="precio" class="form-control" />
                <span asp-validation-for="precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MicroserviceUser/Views/Libros/Index.cshtml
@model IEnumerable<MicroserviceUser.Models.Libro>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (TempData["Mensaje"] != null)
{
    <span>@TempData["Mensaje"]</span>
}
<div>
    <div>
        <div>
            <h3>List De Libros</h3>
        </div>
        <div>
            <a asp-controller="Libros" asp-action="Create">Agregar Libro</a>
        </div>
    </div>
    @if (Model.Count() > 0)
    {
        <table>
            <thead>
                <tr>
                    
                    <td>
                        @Html.DisplayNameFor(m => m.titulo)
                    </td>

                    <td>
                        @Html.DisplayNameFor(m => m.descripcion)
                    </td>

                    <td>
                        @Html.DisplayNameFor(m => m.fechaDeLanzamiento)
                    </td>

                    <td>
                        @Html.DisplayNameFor(m => m.Autor)
                    </td>

                    <td>
                        @Html.DisplayNameFor(m => m.precio)
                    </td>

                    <td>
                        Acciones
                    </td>
                </tr>
            <thead>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.titulo</td>
                        <td>@item.descripcion</td>
                        <td>@item.fechaDeLanzamiento</td>
                        <td>@item.Autor</td>
                        <td>@item.precio</td>
                        <td>
                            <a asp-controller="Libros" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                            <a asp-controller="Libros" asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                        </td>
                    </tr>
                }
            </thead>
        </table>
    }
    else
    {
        <hr/>
        <span>No hay registros XD....</span>

    }

</div>

MicroserviceUser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MicroserviceUser</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MicroserviceUser</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="index">Crud Libros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MicroserviceUser - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>